### ISSUE TITLE
Initially surprising behavior of `sort/2` when used contrary to documented mode.

### ISSUE THREAD

**Issue by aBathologist** [SWI-Prolog/issues#10]
Specs:
- SWI-Prolog version 7.1.30 for x86_64-darwin13.4.0
- OS X 10.9.5

I misused use `sort(+List, -Sorted)`, calling it with `Sorted` as a ground term and `List` as partially instantiated, like so:

``` prolog
?- sort([A,B,3], [1,2,3]).
A = 1,
B = 2.
```

This succeeds just as you'd expect (if ignorant of proper usage). Unaware of my mistake, I continued to misuse the predicate.  However, I soon I discovered that it _seemed_ to fail or succeed depending on which elements of `List` are left free:

``` prolog
?- sort([1,2,C], [1,2,3]).
false.
```

I now understand that this is because `List` will first be sorted to the standard order of terms (`[C,1,2]` in this case) and that does not unify with `[1,2,3]`.  Moreover, I am aware that I shouldn't use the predicates contrary to their documented modes.  My misunderstanding has been corrected. 

However, in ##prolog, I was encouraged to file this issue just in case it crossed over to a level of weirdness that would need addressing. 

To that end, here are some other strange-seeming results that can be obtained: 

``` prolog
?- sort([1,B,3], [1,B,3]).
B = 1.

?- sort([B,A,3], [2,3,3]). % sort is meant to remove duplicates
B = 2,
A = 3.
```

These might be considered alongside the behavior that [Boris](http://www.swi-prolog.org/user/view_profile?user=4d5d9fb0-ea0e-11e2-9118-00144fee017c) remarks in the [`sort/2` documentation](http://www.swi-prolog.org/pldoc/doc_for?object=sort/2).

(I'll also throw in: Thanks for all the hard work on this wonderful software!)

**Comment by JanWielemaker** [comment]
Pushed e6c59ad9c3eb40f2276dbde2469e761719fa5b3d, explaining the details about variable ordering.
