### ISSUE TITLE
Type error: `dict-key' expected, found `a/b' (a compound)

### ISSUE THREAD

**Issue by erikkaplun** [SWI-Prolog/issues#100]
The documentation on dicts has this example ([5.4.1.2 Predefined functions on dicts](https://www.swi-prolog.org/pldoc/man?section=ext-dict-functions)):

```
?- write(t{a:t{b:x}}.get(a/b)).
x
```

however, on SWI Prolog 8.2.0, I get instead:

```
?- write(t{a:t{b:x}}.get(a/b)).
ERROR: Type error: `dict-key' expected, found `a/b' (a compound)
...
```

**Comment by JanWielemaker** [comment]
The docs document the current development version.   Key-paths are a new addition.  `.get(a).get(b)` should work fine, as well as simply `.a.b` which will raise an error rather than failing if a key is missing.
