### ISSUE TITLE
ppc64le compilation failure in Alpine for swi-prolog 8.5.0

### ISSUE THREAD

**Issue by brebs-gh** [SWI-Prolog/issues#104]
Hi, the [compilation log](https://gitlab.alpinelinux.org/ktprograms/aports/-/jobs/515662) for ppc64le (aka [ppc64el in Debian](https://packages.debian.org/sid/ppc64el/swi-prolog/download)) shows failure:

```
/builds/ktprograms/aports/testing/swi-prolog/src/swipl-8.5.0/src/os/../pl-inline.h: In function 'valBignum___LD':
/builds/ktprograms/aports/testing/swi-prolog/src/swipl-8.5.0/src/os/../pl-inline.h:448:2: error: #error "Unsupported int64_t alignment conversion"
  448 | #error "Unsupported int64_t alignment conversion"
```

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/ann-swi-prolog-8-4-1-stable/4661/1

**Comment by brebs-gh** [comment]
All done, closing issue.
