### ISSUE TITLE
Compilation failures in 8.5.4 & 8.5.3 in Alpine Linux

### ISSUE THREAD

**Issue by brebs-gh** [SWI-Prolog/issues#108]
Hi, 8.5.4 has [compilation errors](https://gitlab.alpinelinux.org/brebs/aports/-/pipelines/103462) in Alpine Linux:

* armhf: [failure](https://gitlab.alpinelinux.org/brebs/aports/-/jobs/568555#L3341): library/cql: WAM Table mismatch: wam_table[8(h_mpz)] == wam_table[10(h_string)]
* armv7: [failure](https://gitlab.alpinelinux.org/brebs/aports/-/jobs/568554#L3635): test bigint: assertion failed
* x86 (32-bit): [failure](https://gitlab.alpinelinux.org/brebs/aports/-/jobs/568550#L3628): test bigint: assertion failed

These same compilation errors [also occurred in 8.5.3](https://gitlab.alpinelinux.org/brebs/aports/-/pipelines/103450).

**Comment by JanWielemaker** [comment]
Thanks.  Pushed SWI-Prolog/swipl-devel@1dbf34bb5c760cc8ff7812ac4ef3b4ebaa00a28b to address the bigint issues that affect all 32-bit platforms.   Not really a serious issue, mostly a failing test.   The armhf issue is harder.   Seems the compiler is optimizing  `SEPARATE_VMI` away that it shouldn't.   Need to think about something else that prevents the compiler to squash two labels :cry:

**Comment by JanWielemaker** [comment]
The close was a bit early ...  Pushed SWI-Prolog/swipl-devel@7bf463db4dcc7b4e27c820ef8fc6f94fd8116720 to address the armhf issue.  Haven't tested it.   The current approach is something the compiler cannot legally outsmart us.   It does mean it actually needs to emit some code that shouldn't be necessary.   The impact is not measurable though.

**Comment by brebs-gh** [comment]
The tests [all passed](https://gitlab.alpinelinux.org/brebs/aports/-/pipelines/106040) in the Alpine package for swi-prolog 8.5.5

**Comment by JanWielemaker** [comment]
Thanks for confirming!
