### ISSUE TITLE
Does socket in SWI-Prolog have a big bug?

### ISSUE THREAD

**Issue by lawme** [SWI-Prolog/issues#11]
I wrote a server with Python, and a client with SWI-Prolog.

The client can send message to the server, but can not receive

message sent from server.

The source of two programs are at below.

---

1). The server 

import socket

if "**main**" == **name**:
    try:
        sock = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        sock.bind(('localhost',8888))
        sock.listen(5)
    except:
        print("init socket err!")

```
while True:
    print('\n listren for client...')
    conn,addr = sock.accept()
    print('get client')
    print(addr)

    conn.settimeout(5)
    szBuf = conn.recv(1024)
    print(byt)

    if '0' == szBuf:
        conn.send(b'exit')
    else:
        conn.send(b'welcome client!')

    conn.close()
    print('end of the service')
```

---

2). The client 

:- use_module(library(socket)).

create_client :-
    setup_call_catcher_cleanup(
        tcp_socket(Socket),
        tcp_connect(Socket, localhost:8888),
        exception(_),
        tcp_close_socket(Socket)
    ),
    setup_call_cleanup(
        tcp_open_socket(Socket, In, Out),
        chat_to_server(In, Out),
        close_connection(In, Out)
    ).

close_connection(In, Out) :-
    close(In, [force(true)]),
    close(Out, [force(true)]).

chat_to_server(In, Out) :-
    write(Out,'....... 12345 .........'),
    read(In,Term),
    nl,write(Term),nl.

---

When the client run, the server soon exit and show the error:

Traceback (most recent call last):
  File "D:\PyQt4\learn\sockets\server2.py", line 24, in <module>
    szBuf = conn.recv(1024)
socket.timeout: timed out

The server then stop untill restart the server.

But if delete the predicate, read(In,Term), 
both the client and the server will run normally.

The new clause is as below:

chat_to_server(In, Out) :-
    write(Out,'....... 12345 .........').

Why the problem occurred, and how to correct it?

Thanks advance.

**Comment by JanWielemaker** [comment]
Without looking at all details, my guess is that you need to flush
the output after writing (flush_output(Stream)).

	Cheers --- Jan

**Comment by JanWielemaker** [comment]
As there is no follow up and it is not likely to be a bug, I close this.
