### ISSUE TITLE
Multiple function-like predicate calls without intermediate variables.

### ISSUE THREAD

**Issue by malteneuss** [SWI-Prolog/issues#14]
Sometimes we have predicates func1(Input, Result), func1(Input, Result) that essentially behave like functions. If we want to apply several functions in sequence to a certain input, we currently have to
call the first function, bind its result to a variable and call the second function with that result. This leads to many variables called 'temp'.
In functional programming languages it is possible to compose functions in a "point-free" style which avoids having to name and use explicit temporary variables. This could be imitated in Prolog as well, such as with

``` prolog
compose(F1, F2, F3, Arg, Result) :-
  call(F1, Arg, Temp1) %Get a binding for 'Temp1' 
 ,call(F2, Temp1, Temp2)
 ,call(F3, Temp2, Result)
.
```

However i am not sure how to code it like call/[2..] for an arbitrary number of function predicates.
We could use it as
?- compose(plus(1), plus(2), 1, X)
X = 4.

**Comment by pkoch** [comment]
You can approximate that compose with `foldl(call, [F1, F2, F3], Arg, Result)`, no?

**Comment by JanWielemaker** [comment]
Yip.  Alternatively call_dcg/3 works, as

```
compose(F1, F2, F3, Arg, Result) :-
    call_dcg((F1,F2,F3), Arg, Result).
```
Anyway, such discussions belong on the forum.   Closing.
