### ISSUE TITLE
dif/2 incorrectly fails

### ISSUE THREAD

**Issue by UWN** [SWI-Prolog/issues#15]
?- dif(X-Y,1-2),X=Y, Y = 1.
false. % incorrect

This should succeed, like

?- X=Y, X=1, dif(X-Y,1-2).
X = Y, Y = 1.

Since 5.6.36 or earlier. i3a#332

**Comment by triska** [comment]
Thank you for reporting this!

Could you please try the following change in `dif.pl`: In line 204, please change `fail` to `true`. I think this is the correct fix. Still, I would like to test `dif/2` more systematically before I apply it in master. I also have a few other changes pending which I will apply as soon as we have a good systematic test suite for `dif/2`. Thank you!

Independently, I noticed that the example already works correctly in SWISH, meaning that the SWISH behaviour diverges from the regular toplevel in this respect, which is an issue in its own right.

**Comment by JanWielemaker** [comment]
It is not SWISH.  Works fine in the toplevel of 7.3.2 as well.  I reversed SWI-Prolog/swipl-devel@f28f47e441f9786a3a63d0a1978957788802190e, but that doesn't seem to be the
culprit.  Smells like the attvar changes for call_residue_vars/2 might be related?  I'm not aware of fixing bugs while making these changes. I'll try with different versions and surely add this as a test case to avoid it showing up again.

**Comment by JanWielemaker** [comment]
git bisect blames SWI-Prolog/swipl-devel@36842569e849908036b425502748cf9d9b1ea212.  Further sectioning of the changes blame the optimization performed on variables that are part of already existing structures.  This optimization is no longer possible, which fixed the issue.  I'm not 100% sure what the real reason is why the old optimization failed.  I suspect some trailing issue.

**Comment by triska** [comment]
In the current version, the problem is only moved a different case:

    ?- dif(X-Y, 1-2), X = Y, X = 2.
    false.

I believe the correct fix is to replace, in `dif.pl`, line 204, `fail` by `true`. However, I will collect more systematic test cases before I apply this.

**Comment by JanWielemaker** [comment]
This might explain why the attvar changes affect this case: they affect the order of attvars in
the standard order of terms.

**Comment by UWN** [comment]
While the incorrectness issue is gone, dif/2 is still very weak (compared to other implementations):

?- dif(X-Y, 1-2), X = Y.
X = Y,
dif(f(Y, Y), f(1, 2)).

Expected: Only X = Y.

**Comment by triska** [comment]
I have installed a patch that fixes this, please try it out. Thank you!

**Comment by JanWielemaker** [comment]
This seems fixed
