### ISSUE TITLE
reverse(Xs,[a]) leaves a choice point open

### ISSUE THREAD

**Issue by UWN** [SWI-Prolog/issues#17]
?- reverse(Xs,[a]).
Xs = [a] ;
false.

Expected: Xs = [a].  No open choice point.

Indexing heuristics is misguided.
Fix: Exchange arguments of auxiliary predicate lists:reverse/4 from
reverse(Es,Xs0,Xs,Bound) to reverse(Es,Bound,Xs0,Xs)

Item#675

**Comment by JanWielemaker** [comment]
Clever!   Happy to apply, provided you state here I can legally distribute the result using the BSD-2 license.

**Comment by UWN** [comment]
>  legally

What is the purpose of this here? It is a minor tweak, clearly beyond the threshold of originality.

**Comment by JanWielemaker** [comment]
> clearly beyond the threshold of originality.

If that is your opinion, there is no problem.  Applied.   Thanks.
