### ISSUE TITLE
gc bug with freeze/2 call_residue_vars/2

### ISSUE THREAD

**Issue by UWN** [SWI-Prolog/issues#19]
Item#677

r :- freeze(_,false), r.

Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.3-16-g270f502)
...
?- [user].
r:-freeze(_,false),r.
|: end_of_file.

true.

?- call_residue_vars(r,Vs).
[Thread 1] pl-gc.c:1061: link_attvars: Assertion failed: t
C-stack trace labeled "crash":
  [0] save_backtrace() at tai_unpack.c:0 [0x7f1bed40a17b]
  [1] __assert_fail() at ??:0 [0x7f1bed3ce2a1]
  [2] garbageCollect() at tai_unpack.c:0 [0x7f1bed38dfd4]
  [3] ensureGlobalSpace() at tai_unpack.c:0 [0x7f1bed38e27c]
  [4] m_qualify_argument() at pl-wam.c:0 [0x7f1bed355b40]
  [5] PL_next_solution() at ??:0 [0x7f1bed362475]
  [6] query_loop() at tai_unpack.c:0 [0x7f1bed3a111f]
  [7] prologToplevel() at tai_unpack.c:0 [0x7f1bed3a197f]
  [8] PL_toplevel() at ??:0 [0x7f1bed35d2c5]
  [9] /opt/gupu/swipl-devel/bin/swipl(main+0x35) [0x4007e5]
  [10] ??() at ??:0 [0x7f1becd7576d]
  [11] /opt/gupu/swipl-devel/bin/swipl(+0x82d) [0x40082d]
[FATAL ERROR:
	Received signal 6 (abrt) while in 3-th garbage collection]
[Thread 1]: local-overflow: spare=0 (def=4096)
Last resource exception:
No backtrace named exception
Out of local-stack.  No room for exception term.  Aborting.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with SWI-Prolog/swipl-devel@c34187290bbbf3de0362adf1a3ebcc58d7c1c733.

**Comment by jburse** [comment]
Reclaiming frozen goals is not valid in certain settings. For example in CC this would not be allowed, since a program has at least 3 outcomes:

There is a paper by Evan Tick explaining CC:

    A program successfully terminates when, starting from an initial user query (a conjunct of atoms), after some number of reduction steps, no goals remain to be executed, nor are suspended. Alternatively, the program deadlocks if only suspended goals remain. A third result is program failure, which is defined more formally below.

THE DEEVOLUTION OF CONCURRENT LOGIC PROGRAMMING LANGUAGES Evan Tick - 1995 https://core.ac.uk/download/pdf/82787481.pdf

**Comment by JanWielemaker** [comment]
With `call_residue_vars/1` frozen goals are not garbage collected.  That is the whole point.  Without, they are as they are not accessible and thus will never wake up anyway.

**Comment by JanWielemaker** [comment]
> Does call_residue_vars/2 in general block garbage collection?

No.  The implementation of this predicate is really tricky and went through several iterations.  Eventually, with some help from Bart Demoen, I found an efficient and correct way to implement it. It is all in the sources though.

**Comment by jburse** [comment]
So library(pio) will not anymore run, when I call it with call_residue_vars/2 ?

**Comment by JanWielemaker** [comment]
Why not?  As said, GC works fine.  Only programs creating an infinite number of residue vars will run out of memory.   Instead of asking you can also test.

**Comment by jburse** [comment]
Because as soon as you place call_residue_vars/2, the frozen goals will not anymore be reclaimed. I will probably try this test case with call_residue_vars/2 around it:

https://stackoverflow.com/q/31095081/502187

**Comment by jburse** [comment]
Here is the result:

![image](https://user-images.githubusercontent.com/5411487/48209740-26b76780-e376-11e8-830b-7e5b6be37349.png)

**Comment by jburse** [comment]
It seems a problem of time/1, with statistics/0 around, there is no error. And since I use underscore _ in the call_residue_vars/2, stuff gets even GCed. Only when I use a named variable stuff gets not GCed, but OPs example will result in a big listing from the top-level and not crash without time/1.

**Comment by JanWielemaker** [comment]
Nope.  Was a GC issue failing to make sufficient room to protect the attvars.  Pushed 
b78e03b48f74a5378b0ecd9e0dc12118ad65ef61 to resolve this.

**Comment by jburse** [comment]
Yes, its not time/1 dependent. I was doing more testing.

**Comment by jburse** [comment]
Yes, its not time/1 dependent. I was doing more testing.

test(X,Y) :-
   statistics(stacks, X),
   length(Zs,1000), big_freeze_test(1,500,Zs),
   statistics(stacks, Y).

test2(X,Y) :-
   statistics(stacks, X),
   call_residue_vars((length(Zs,1000), big_freeze_test(1,500,Zs)), T),
   statistics(stacks, Y),
   T == T.

Results, if there is no crash:

?- test(X,Y).
X = [2176, 1320],
Y = [506704, 1232].

?- test2(X,Y).
X = [2184, 1328],
Y = [97917544, 1328].
