### ISSUE TITLE
pretty printing in version 7.2.x does not work like in version 6.6.x

### ISSUE THREAD

**Issue by joseph-vidal-rosset** [SWI-Prolog/issues#20]
Hello, 
I'm using a prover in Prolog written by Naoyuki Tamura: seqprover.pl that you can donwload here: http://bach.istc.kobe-u.ac.jp/seqprover/seqprover.pl . Consult seqprover.pl and then type:
prover.
Then you can test formulas in first order logic, like this one for example: 
X@p(X) --> p(a)/\p(b)
With version 6.6.x of SWI-Prolog, you get the same output in pretty printing that in SICTUS, i.e. :+1: 
-------------------- Ax  -------------------- Ax
p(a),X@p(X) --> p(a)     p(b),X@p(X) --> p(b)
-------------------- L@  -------------------- L@
  X@p(X) --> p(a)          X@p(X) --> p(b)
  ---------------------------------------- R/\
           X@p(X) --> p(a)/\p(b)

(Have a look on this prover online here : http://bach.istc.kobe-u.ac.jp/seqprover/ )
with version 7.2.x  there is no more pretty printing for these formulas, and I guess that the problem comes from the @ or the # (used as name for  quantifiers in this program) because this problem does not occur with test of propositional formulas. 
I hope that this problem can be solved... 
Best wishes,
Jo.

**Comment by JanWielemaker** [comment]
It is caused by the new SWI-Prolog 7 string syntax.  Works when applying the following patch,
which also works with SICStus.  Please try to get this integrated upstream.

```
diff --git a/seqprover.pl b/seqprover.pl
index a343173..d4b6bc3 100644
--- a/seqprover.pl
+++ b/seqprover.pl
@@ -500,12 +500,12 @@ name_variables(X, N0, N, Vs0, Vs, Z) :-
 	name_variables(Xs, N0, N, Vs0, Vs, Zs),
 	Z =.. Zs.
 
-name_var(0, VN, X) :- !, name_var1("X", VN, X).
-name_var(1, VN, X) :- !, name_var1("Y", VN, X).
-name_var(2, VN, X) :- !, name_var1("Z", VN, X).
+name_var(0, VN, X) :- !, name_var1(0'X, VN, X).
+name_var(1, VN, X) :- !, name_var1(0'Y, VN, X).
+name_var(2, VN, X) :- !, name_var1(0'Z, VN, X).
 
-name_var1([V], 0, X) :- !, name(X, [V]).
-name_var1([V], VN, X) :-
+name_var1(V, 0, X) :- !, name(X, [V]).
+name_var1(V, VN, X) :-
 	name(VN, Ns),
 	name(X, [V|Ns]).
 
```

**Comment by joseph-vidal-rosset** [comment]
Many thanks Jan. I am very impressed by your reactivity. 
Do you mean that I have to copy and paste these lines in seqprover.pl and deleting other lines? Sorry but I am not at all an expert, but just an amateur. More detailed explanations on what I have to do are welcome. I wish to tell you if it works in order to help in turn (at the moment I have downgrade my Debian from testing to stable, in order to avoid this new version of SWI-Prolog... ).

**Comment by JanWielemaker** [comment]
varieOn 08/01/15 19:42, Joseph Vidal-Rosset wrote:
> Many thanks Jan. I am very impressed by your reactivity.

It varies ...

> Do you mean that I have to copy and paste these lines in seqprover.pl
> and deleting other lines? Sorry but I am not at all an expert, but just
> an amateur. More detailed explanations on what I have to do are welcome.se

Either use the patch program or patch by hand.

> I wish to tell you if it works in order to help in turn (at the moment I
> have downgrade my Debian from testing to stable, in order to avoid this
> new version of SWI-Prolog... ).

Should be simpler.

	--- Jan

**Comment by joseph-vidal-rosset** [comment]
Dear Jan (cc. Naoyuki),

I have tried to apply your patch (following the Ubuntu documentation on patch), but the patched file did not work. Then I have tried to understand how to change these line in seqprover.pl in order to fix the pretty printing and also the output in LaTeX code for proof.sty. The good news is that I have succeeded. That's why I will forward to this post to Naoyuki Tamura.

In the seqprover.pl presently on the web the following lines (from 503 to 510 in my emacs):

> name_var(0, VN, X) :- !, name_var1("X", VN, X).
> name_var(1, VN, X) :- !, name_var1("Y", VN, X).
> name_var(2, VN, X) :- !, name_var1("Z", VN, X).

> name_var1([V], 0, X) :- !, name(X, [V]).
> name_var1([V], VN, X) :-
>	name(VN, Ns), 
>	name(X, [V|Ns]).

and also these ones concerning the output in LaTeX (from line 684 to 692'): 

> tex_name_var(0, VN, X) :- !, tex_name_var1("x", VN, X).
> tex_name_var(1, VN, X) :- !, tex_name_var1("y", VN, X).
> tex_name_var(2, VN, X) :- !, tex_name_var1("z", VN, X).

> tex_name_var1([V], 0, X) :- !, name(X, [V]).
> tex_name_var1([V], VN, X) :-
>	[C1,C2]="_{",
>	name(VN, Ns), append(Ns, "}", Ns1),
>	name(X, [V,C1,C2|Ns1]).

must be changed respectively by:

> name_var(0, VN, X) :- !, name_var1('X', VN, X).
> name_var(1, VN, X) :- !, name_var1('Y', VN, X).
> name_var(2, VN, X) :- !, name_var1('Z', VN, X).

> name_var1(V, 0, X) :- !, name(X, [V]).
> name_var1(V, VN, X) :-
>	name(VN, Ns), 
>	name(X, [V|Ns]).

and 

> tex_name_var(0, VN, X) :- !, tex_name_var1('x', VN, X).
> tex_name_var(1, VN, X) :- !, tex_name_var1('y', VN, X).
> tex_name_var(2, VN, X) :- !, tex_name_var1('z', VN, X).

> tex_name_var1(V, 0, X) :- !, name(X, [V]).
> tex_name_var1(V, VN, X) :-
> 	[C1,C2]="_{",
>	name(VN, Ns), append(Ns, "}", Ns1),
>	name(X, [V,C1,C2|Ns1]).

and again the pretty printing and LaTeX output work with SWI-Prolog 7.2.x when one test a valid formula in predicate calculus. 

I confess that I do not understand why 

> name_var1([V], ...  

and 

> tex_name_var1([V], ...

must now be written

> name_var1(V, ...

and

> tex_name_var1(V, ...

Jan, if you can find time to give us an explanation, you are welcome. My warmest thanks for your help. 
Best wishes,
Jo.
