### ISSUE TITLE
outdated http_cors.pl library in the ClioPatria package

### ISSUE THREAD

**Issue by sklarman** [SWI-Prolog/issues#22]
I'm not an experienced user but I've observed the following issue. 

The http_cors.pl library in the cliopatria/lib/http location, that comes with the recent cliopatria installation package, seems to be causing trouble when making a pengine call to the cliopatria server from javascript code in Chrome. This ends up in the following error report:

- Failed to load resource: the server responded with a status of 500 (Internal Server Error) http://localhost:3020/pengine/create
- XMLHttpRequest cannot load http://localhost:3020/pengine/create. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 500. 

Everything still works fine in IE or when making a call from another prolog process. Can't explain the precise reasons, but things got fixed when I deleted the file and thus (probably) redirected cliopatria to use the corresponding library from the swipl repository.

Cheers,
Szymon

**Comment by JanWielemaker** [comment]
Thanks.  Removed from ClioPatria.
