### ISSUE TITLE
a bug in Pengine's change_passwd.pl library

### ISSUE THREAD

**Issue by sklarman** [SWI-Prolog/issues#23]
On registering the admin for the first time a pengine's server is installed you get an error report:

Username (default: "admin")? admin
Password (will be ECHOED)? admin
ERROR: c:/users/szymon/google drive/myapplications/clio+pengines/pengines-master/run.pl:8:
        Type error: `atomic' expected, found `[97,100,109,105,110]' (a list)

The problem lies in the following clause in the change_passwd.pl library :

check_passwd(File) :-
	print_message(warning, pengine(no_admin_passwd)),
	nl(user_output),
	ask('Username (default: "admin")? ', User, admin),
	ask('Password (will be ECHOED)? ', Passwd, _),
	change_passwd(File, User, Passwd).

The following revision fixes it:

check_passwd(File) :-
	print_message(warning, pengine(no_admin_passwd)),
	nl(user_output),
	ask('Username (default: "admin")? ', User, admin),
	ask('Password (will be ECHOED)? ', Passwd, _),
        atom_codes(UserAtom, User),
	change_passwd(File, UserAtom, Passwd).

Cheers,
Szymon

**Comment by JanWielemaker** [comment]
Thanks.  Fixed.
