### ISSUE TITLE
Using `w` causes all subsequent queries to write the complete terms in variable bindings

### ISSUE THREAD

**Issue by borisvassilev** [SWI-Prolog/issues#24]
Observed on the latest development release, while playing around on the top level.

Here is a simple way to reproduce:

```prolog
?- Codes = `This is a code list` ; false.
Codes = [84, 104, 105, 115, 32, 105, 115, 32, 97|...] [write]
Codes = [84, 104, 105, 115, 32, 105, 115, 32, 97, 32, 99, 111, 100, 101, 32, 108, 105, 115, 116] .

?- numlist(1, 1000, L). % You get a nice wall of numbers
```

Is that a feature?

**Comment by JanWielemaker** [comment]
It has always been that way.  Some people like full output.  For some projects that is ok.  I don't see
a good solution that will make everyone in all projects happy.
