### ISSUE TITLE
edit doesnt work in version 7.2.0-2

### ISSUE THREAD

**Issue by shaolintl** [SWI-Prolog/issues#25]
On Debian stretch, kernel 4.0.9-040009.
I installed version 7.2.0-2 and calling edit/0 or edit/1 threw:
ERROR: toplevel: Undefined procedure: edit/0 (DWIM could not correct goal)

Trying the same with version 6.6.6-5 works fine.
4.0.9-040009
I looked (briefly) in the latest swi-prolog guide and could not find a reason for the different behavior.

**Comment by JanWielemaker** [comment]
Closing old issue due to no follow up.   Almost surely a bug of the packager.
