### ISSUE TITLE
build warns, but reference does not exists: http://www.swi-prolog.org/build/issues/bdb.html

### ISSUE THREAD

**Issue by jrvosse** [SWI-Prolog/issues#26]
during the build, swipl -g check_installation,halt -t 'halt(1)'
detects:

Warning: library(bdb) .......................... NOT FOUND
Warning: See http://www.swi-prolog.org/build/issues/bdb.html

But the last uri gives a 404...

**Comment by JanWielemaker** [comment]
Thanks for reminding.  Fixed
