### ISSUE TITLE
directory_file_path returns non-canonical path

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/issues#29]
Welcome to SWI-Prolog (Multi-threaded, 32 bits, Version 7.3.0)

1 ?- directory_file_path(D, F, 'foo/bar').
D = foo,
F = bar.

2 ?- directory_file_path(D, bar, 'foo/bar').
D = 'foo/'.

**Comment by JanWielemaker** [comment]
Fixed with SWI-Prolog/packages-clib@3368a2c3a5a89f8600b7da896c5cae0c3096c864
