### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by stefan-kral** [SWI-Prolog/issues#33]
Hello.

I have implemented a predicate `ith0_list_member/3` which is based on clpfd.
It sucks performance-wise, but that's besides the point.

The point is that SWI-Prolog crashes (sometimes, sometimes not):
- If I do it <b>exactly</b> like in the snippet below, I have crashed every single time I tried so far.
- If I use the Prolog toplevel for a little while and THEN do it, I have not observed any crashes so far.

HTH! Thank you!

All the best, stefan.

---

<pre>
stefan@Lenovo-G510 ~ $ uname -a
Linux Lenovo-G510 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

stefan@Lenovo-G510 ~ $ swipl
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.15)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

?- use_module(library(clpfd)).
true.

?- [user].
ith0_list_member(0, [E|_], E).
ith0_list_member(I, [_|Es], X) :-
   I #> 0,
   I0 #= I-1,
   ith0_list_member(I0, Es, X).
|: |: |: |: |: 
true.

?- length(Es,1000), time((between(1,1000,_),ith0_list_member(N,Es,X),false;true)).
[Thread 1 (main) at Wed Jan 20 18:22:20 2016] pl-attvar.c:174: assignAttVar: Assertion failed: (__PL_ld->stacks.global.top)+8 <= (__PL_ld->stacks.global.max) && (__PL_ld->stacks.trail.top)+6 <= (__PL_ld->stacks.trail.max)
C-stack trace labeled "assert_fail":
  [0] PL_strtod() at ??:? [0x7f8200265420]
  [1] __assert_fail() at ??:? [0x7f8200228331]
  [2] destroySourceFile() at ??:? [0x7f820023393b]
  [3] destroySourceFile() at ??:? [0x7f8200233a51]
  [4] PL_next_solution() at ??:? [0x7f82001c2af0]
  [5] pl_skip_list3_va() at ??:? [0x7f82001fc28e]
  [6] pl_skip_list3_va() at ??:? [0x7f82001fca10]
  [7] PL_toplevel() at ??:? [0x7f82001b98cd]
  [8] swipl(main+0x2d) [0x40083d]
  [9] __libc_start_main() at ??:? [0x7f81ffbcbec5]
  [10] swipl(+0x881) [0x400881]
stefan@Lenovo-G510 ~ $
</pre>

**Comment by JanWielemaker** [comment]
Hi Stefan,

The message strongly suggests this is an issue that is already fixed in
the git version.

	--- Jan

**Comment by stefan-kral** [comment]
Hi Jan.

That's great, I'll check it out ASAP. Up to now, I have been using the
Ubuntu PPA (out of complanency); I'm switching to git.

Thank you!

cheers Stefan.

**Comment by JanWielemaker** [comment]
As there is no follow up, I assume this can be closed.
