### ISSUE TITLE
Undefined predicate: $set_source_module/1

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/issues#34]
On a machine where the latest build was from a git checkout around Dec. 28th, I have now pulled the latest git version. Upon `make`, I get:

<pre>
...
cp ./SWI-Prolog.h ../include/SWI-Prolog.h
rm -f swipl.prc
./swipl.sh -O -o swipl.prc -b ../boot/init.pl
Loading boot file ...
[PROLOG SYSTEM ERROR:  Thread 1 (main) at Sat Jan 23 19:27:04 2016
	Undefined predicate: $set_source_module/1

PROLOG STACK:
]
</pre>

When I do `make clean`, followed by `make`, I get the same message.

Eventually, I fixed this issue with `git clean -fx`. After that, `./configure && make` compiled the system successfully.

If possible, please update the make dependencies so that `make` suffices in such cases.

**Comment by JanWielemaker** [comment]
Not really intending.  It is a lot of work to sort it all out.  When in doubt, do `make distclean` and then
`make`.
