### ISSUE TITLE
Attvars ignoring some wakeups

### ISSUE THREAD

**Issue by logicmoo** [SWI-Prolog/issues#35]
````

dmsg(M):- format(user_error,'~N~q.~n',[M]),flush_output(user_error).

tAA:verify_attributes(Var, Value, [get_attrs(CVar,AttrsNow),dmsg(tAA:goal_for(Name,Attrs=AttrsNow))]):- copy_term(Var,CVar),sformat(Name,'~w',Var), ignore(get_attrs(Var,Attrs)),dmsg(tAA:va(Var,Value,[])=Attrs).
tBB:verify_attributes(Var, Value, [get_attrs(CVar,AttrsNow),dmsg(tBB:goal_for(Name,Attrs=AttrsNow))]):- copy_term(Var,CVar),sformat(Name,'~w',Var), ignore(get_attrs(Var,Attrs)),dmsg(tBB:va(Var,Value,[])=Attrs).


va(X):- put_attr(X,tAA,'AAA').
vb(X):- put_attr(X,tBB,'BBB').


````

% swi prolog ignores peer wakeups ..
The following output is incorrect...

````
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.15-29-g6a6915a)
Copyright (c) 1990-2015 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

1 ?- va(A),vb(B),A=B.
tBB:va(_G294746,_G294739,[])=att(tBB,'BBB',[]).
tBB:goal_for("_G294746",att(tBB,'BBB',[])=att(tBB,'BBB',[])).
A = B,
put_attr(B, tAA, 'AAA').

2 ?- vb(B),va(A),A=B.
tAA:va(_G294734,_G294727,[])=att(tAA,'AAA',[]).
tAA:goal_for("_G294734",att(tAA,'AAA',[])=att(tAA,'AAA',[])).
B = A,
put_attr(A, tBB, 'BBB').
````

Here is this corrected...
````
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.15-33-g5524040-DIRTY)

1 ?- va(A),vb(B),A=B.
tAA:va(_G319347,_G319354,[])=att(tAA,'AAA',[]).
tBB:va(_G319354,_G319347,[])=att(tBB,'BBB',[]).
tBB:goal_for("_G319354",att(tBB,'BBB',[])=att(tBB,'BBB',[])).
tAA:goal_for("_G319347",att(tAA,'AAA',[])=att(tAA,'AAA',[])).
A = B,
put_attr(B, tAA, 'AAA').

2 ?- vb(B),va(A),A=B.

tAA:va(_G319354,_G319347,[])=att(tAA,'AAA',[]).
tBB:va(_G319347,_G319354,[])=att(tBB,'BBB',[]).
tBB:goal_for("_G319347",att(tBB,'BBB',[])=att(tBB,'BBB',[])).
tAA:goal_for("_G319354",att(tAA,'AAA',[])=att(tAA,'AAA',[])).
B = A,
put_attr(A, tBB, 'BBB').
````

**Comment by JanWielemaker** [comment]
Why is this the case?  There is one attvar assigned to another that has one attribute.  That leads to one verify_attributes/3 call.   That is how it is defined right now.  Whether or not that is a good idea is another issue.  Right now, I only want to _know_ why the _sat_ case goes wrong.

**Comment by logicmoo** [comment]
Both attributed variables have different attribute modules..

 tAA   tBB

  Neither system understands the details of the other module (tAA doesn't
understand what the tBB attributes mean).. for example   tAA might mean ">#
10"  tBB might mean "#<12"   they could be implemented to both call use
CLP(FD) to set these constraints..  however since we ignore either tAA or
tBB .. will the answer 11 ever be findable?

**Comment by JanWielemaker** [comment]
All true, but this issue is already the case for the unify_attr_hook/2 case as well.  It probably means we need to reconsider in what modules verify_attributes is called, but first we need to understand why the current hook seems to mess up.  That is most likely not caused by this issue.

**Comment by logicmoo** [comment]
On Sun, Jan 24, 2016 at 5:20 AM, Jan Wielemaker <notifications@github.com>
wrote:

> All true, but this issue is already the case for the unify_attr_hook/2
> case as well. It probably means we need to reconsider in what modules
> verify_attributes is called, but first we need to understand why the
> current hook seems to mess up. That is most likely not caused by this issue.
>

Right, so for example was clp(fd) is leveraging freeze/2 in zcompare/3 and
we are ignoring freeze:verify_attrbutes/3  or are we ignoring
 clpfd:verify_attrbutes/3 in our case we ignore freeze/2 since it is
younger.  This is not a problem for attr_unify_hook since two attvars are
very unlikely since at least has already been woken up.  In
verify_attributes/3 neither is woken by the time the first one wakes.

**Comment by logicmoo** [comment]
Sorry we don't "ignore freeze/2" we merely forget it ever existed.
since clpfd:verify_attrbutes/3
 manages its attributes and didn't realize it was supposed to *also*
supposed to copy the freeze co-routines.

**Comment by logicmoo** [comment]
Markus even almost says this..

> Note the main difference to the version above: Using the continuation
goals, the call of fd_put/3 is now delayed until *after* verify_attributes/3.


If he puts the constraints too early they seem to be forgotten about.
https://github.com/SWI-Prolog/swipl-devel/issues/108

**Comment by logicmoo** [comment]
wrong issue repository
