### ISSUE TITLE
Meaning of [user] changed from reconsult to consult.

### ISSUE THREAD

**Issue by UWN** [SWI-Prolog/issues#37]
(Item#680)

Old (and preferable):

<pre>
/usr/bin/swipl -f none
% library(swi_hooks) compiled into pce_swi_hooks 0.00 sec, 3,856 bytes
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 5.10.4)
Copyright (c) 1990-2011 University of Amsterdam, VU Amsterdam
...

?- [user].
a(1).
|: % user://1 compiled 0.00 sec, 712 bytes
true.

?- [user].
a(2).
Warning: user://2:15:
	Redefined static procedure a/1
|: % user://2 compiled 0.01 sec, 408 bytes
true.
</pre>

Still like that in 7.3.11-29-g8ac682e. Change before 7.3.14-42-ga83e0df:

<pre>
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.3.14-42-ga83e0df)
...
?- [user].
a(1).
|: true.

?- [user].
a(2).
|: true.

?- a(X).
X = 1 ;
X = 2.
</pre>
Expected: No answer `X = 1`

**Comment by JanWielemaker** [comment]
Actually redefinition in general was broken.  Fixed with SWI-Prolog/swipl-devel@70e8acc2ae4af41667f3b78cfbe6290ac21ca553
