### ISSUE TITLE
subtract/3 behavior based on unification, while ord_subtract/3 is not!

### ISSUE THREAD

**Issue by jrvosse** [SWI-Prolog/issues#4]
Dear all,

I just found out (the hard way) that ord_subtract/3 is _not_ based on unification like its unordered sister:

?- subtract([1,2],[A],R).
A = 1,
R = [2].

?- ord_subtract([1,2],[A],R).
R = [1, 2].

Jan, is this a bug or a feature?  If the latter, this should be made clear from the documentation....

From the current man pages:
subtract(+Set, +Delete, -Result)
Delete all elements in Delete from Set. Deletion is based on unification using memberchk/2. The complexity is |Delete|*|Set|.

ord_subtract(+InOSet, +NotInOSet, -Diff)
Diff is the set holding all elements of InOSet that are not in NotInOSet.

**Comment by aBathologist** [comment]
I just submitted an issue regarding the behavior of `sort/2` when used variables (but also against its documented mode). I realized on reflection that my issue is related to this one: namely, they are both results of ordering according the standard order of terms. For sake of preserving the standard order of terms, of course, unification cannot be carried out. In the case of `ord_subtract/3`, I believe the behavior you observe is accounted for in [the general documentation of `library(ordsets)`](http://www.swi-prolog.org/pldoc/man?section=ordsets): 

> The ordsets library is based on the standard order of terms. This implies it can handle all Prolog terms, including variables.

This kind of behavior could be made extra clear if the mode documentation where instead `ord_subtract(@InOSet, @NotInOSet, -Diff)`, however, the fact that some unification can be forced by violating the mode on the third argument probably makes this problematic; for, I just discovered, abuse of `ord_subtract/3` counter to it's documented mode can be made to yield unification puzzles akin to those I noticed with `sort/2`:

```prolog
?- ord_subtract([B,1,3],[A,1,2], [A,B]). 
B = A, A = 3.
```

**Comment by JanWielemaker** [comment]
The story about handling variables and ordered representations was recently updated (not on the site yet).  It is rather complex, but unavoidable as this is how Prolog works.  It is a bit hard to repeat this story all over the place, so I'm afraid we must live with this.

A very long term solution may to assign properties to predicates, something such as most Unix API functions that are thread-safe, reentrant, signal-safe, etc.  If such features were part of the predicate properties we could have an automatically generated block with each predicate.  Closing for now.
