### ISSUE TITLE
env variable corrupted around char 1020 (7.3.30 64-bit Windows)

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/issues#49]
In 7.3.30 64-bit on Windows 10 Pro, Environment variables longer than 1019 chars are reported by getenv/2 with correct length but with incorrect chars from 1020 onwards, perhaps including nul, sometimes other text.

This batch file (renamed from .bat to .txt for GitHub upload) demonstrates it:
[t.txt](https://github.com/SWI-Prolog/issues/files/592616/t.txt)

set z=..................................................
set z=%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%%z%
set z=%z%abcdefghijklmnopqrstuvwxyz
rem 50*20 = 1000 dots plus alphabet = 1026 chars
swipl-win.exe -g 'getenv(z,A),atom_length(A,N),write(N-A),nl'

NB this is not (simply) due to length restrictions in Windows; Java correctly offers env vars of this length and longer e.g. 5000 chars.

Typically, only PATH reaches this length, and jpl:setup_jvm barfs on PATH elements containing nul, which is how I spotted this.

cheers - Paul Singleton

**Comment by JanWielemaker** [comment]
You're entitled for the Nobel prize!   This was brought up many times, but nobody found a properly
reproducible case.   This was easy, I even could just use setenv/2 from Prolog to reproduce the
problem.  Fixed.  If tonights daily builds properly you can enjoy.
