### ISSUE TITLE
format_time/3 doesn't always correctly format time

### ISSUE THREAD

**Issue by OskarSigvardsson** [SWI-Prolog/issues#5]
[The documentation for the format_time/3 predicate](http://www.swi-prolog.org/pldoc/man?predicate=format_time/3) states that the %I conversion prints "the hour as a decimal number using a 12-hour clock (range 01 to 12).", so you can use it to print out "American" style time, with AM/PM. 

It doesn't, however, it prints out values in the range 00-11, which is incorrect. For instance: 

```
?- D = date(2014,11,6,12,30,0,0,'UTC',false), format_time(current_output, "%I:%M %p", D).
00:30 pm
D = date(2014, 11, 6, 12, 30, 0, 0, 'UTC', false).
```

This should print out "12:30 pm", but it prints out "00:30 pm" instead. In addition, the %r conversion also has this problem: 

```
?- D = date(2014,11,6,12,30,0,0,'UTC',false), format_time(current_output, "%r", D).
00:30:00 pm
D = date(2014, 11, 6, 12, 30, 0, 0, 'UTC', false).
```

Also, according to the documentation, the %p conversion should print out "AM" or "PM" in upper-case (this is also the behavior of strftime(), I believe), but it actually prints it in lower-case. 

I get these results on SWI-Prolog 7.1.16 on Mac OS X, if it makes a difference.

**Comment by JanWielemaker** [comment]
Just modified your program by adding `setlocale(LC_ALL, "")`, which causes `%p` to write `pm`.   Running the program with `LANG=C` does give the promised PM.   Will add a remark in the manual.   I think we should not hack around this in Prolog.
