### ISSUE TITLE
SWISH bug parsing term with 'table'

### ISSUE THREAD

**Issue by mcalejo** [SWI-Prolog/issues#51]
The following succeeds on SWI Prolog:

XX = ( Block \= table, location(_,Block) ).

... but it reports a syntax error on SWISH (last github version, 38d02d2)

XX = ( Block \= table, location(_,Block) ).
                                   ^
Syntax error: Operator expected

Changing 'table' to some other atom (or putting () around Block \= table ) removes the error

**Comment by JanWielemaker** [comment]
SWISH preloads library(tabling) which defines `table` as an operator.  Use `Block = (table)` or, SWI-Prolog specific: `Block = 'table'`.
