### ISSUE TITLE
`.` is hijacked by dict and not available for normal use .

### ISSUE THREAD

**Issue by kintalken** [SWI-Prolog/issues#55]
?- (K='yf';K='yfx';K='fx'),op(10'1,K,'.'),false.
false.

?- current_op(P,K,'.').
P = 1,
K = fx ;
P = 1,
K = yfx ;
P = 1,
K = yf.

?- (.a.b.c.)=A.
ERROR: Type error: `dict' expected, found `'.'a' (a compound)
?- 
COMPARE yap : 
  ?- A=(.a|b|c.).
A = ('.'a '|' b '|''.'c)

**Comment by JanWielemaker** [comment]
On 04/10/2017 04:16 PM, kintalken wrote:
> ?- (K='yf';K='yfx';K='fx'),op(10'1,K,'.'),false.
> false.
>
> ?- current_op(P,K,'.').
> P = 1,
> K = fx ;
> P = 1,
> K = yfx ;
> P = 1,
> K = yf.
>
> ?- (.a.b.c.)=A.
> ERROR: Type error: |dict' expected, found|'.'a' (a compound)
> ?-
> COMPARE yap :
> ?- A=(.a|b|c.).
> A = ('.'a '|' b '|''.'c)

That is true. In fact, the syntax is not hijacked, but terms of the form
A.B are. If you really need it you can use term_expansion/2 to translate
A.B terms into something else. That preserves the syntax while avoiding
a conflict with ./2-based functional notation.

	Cheers --- Jan

**Comment by JanWielemaker** [comment]
This has been discussed many times.  `.` is not usable for the ordinary user, nor in classical Prolog, neither in SWI-Prolog V7.  Just try this to see one unexplainable issue.

```
   ?- ct2 (plweb; master) 3_> yap
% Restoring file /home/jan/lib/Yap/startup.yss
YAP 6.2.2 (x86_64-linux): Sat May  7 10:37:03 CEST 2016
MYDDAS version MYDDAS-0.9.1
   ?- A = (a.b.c).
A = [a,b|c]
   ?- A = (1.0.c).
A = [1.0|c]
```
