### ISSUE TITLE
swipl 7.4.2 / qsave_program crashes with option --traditional

### ISSUE THREAD

**Issue by mihanus** [SWI-Prolog/issues#61]
The PAKCS Debian package produces a bug with the newest SWI-Prolog version:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871194

The reason for this is a bug in SWI-Prolog 7.4.2 (I installed it in a Ubuntu 16.04 system) where the predicate `qsave_program` crashes with the option `--traditional`:

    > swipl --traditional
    Welcome to SWI-Prolog (threaded, 64 bits, version 7.4.2)
    SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
    Please run ?- license. for legal details.
    
    For online help and background, visit http://www.swi-prolog.org
    For built-in help, use ?- help(Topic). or ?- apropos(Word).
    
    ?- qsave_program(xxx).
    ERROR: /opt/swiprolog/swi742/lib/swipl-7.4.2/library/qsave.pl:459:7: Syntax error: Operator expected
    ...

It works without the option `--traditional` or also with SWI-Prolog 7.2.3 (which has been used to build the origin PAKCS Debian package).

**Comment by JanWielemaker** [comment]
I tried a fix for the initial syntax error, but they go on and on while the code must be rewritten in a old style I do not like.  As foreseen, `--traditional` would gradually degrade beyond the basic starting the system, defining basic predicates and run it.   More and more of the libraries and tools are no longer compatible with this option.

Porting PAKCS is probably little work.   There is only a small set of traditional Prolog code that does not work and this can typically easily be modified such that it runs both on traditional systems and current SWI-Prolog.  See notably [Adapting code for double quoted strings](http://www.swi-prolog.org/pldoc/man?section=ext-dquotes-port).

**Comment by mihanus** [comment]
Although I can understand this, it is a pity that a minor version increase requires the rewriting of existing code.

I tried this for PAKCS and the necessary changes are numerous. It concerns not only the new interpretation of double quoted strings, but also the different list constructor and the fact the the empty list constructor is no longer an atom required some hacks. The changes are small but finding the right places and modifying them so that the code still runs with ISO-Prolog systems is non-trivial in such a large code base.

**Comment by JanWielemaker** [comment]
Quite likely the changes to SWI-Prolog are smaller :)  Still, it will come back every release as `--traditional` is hardly maintained.  I've ported two huge project and have been involved in another project, counting for over 2M lines of code over the three projects.  That took altogether just a couple of days and gave the confidence that v7 is compatible enough.  For two of the three, compatibility with ISO had to be kept in place.

I see you are developer/contact for the PAKCS project.  Do you want me to have a look how complicated such a port would be and are you at least in theory willing to accept the patches?

P.s.  version numbering is hard :).  I think you should shift the numbers by one place for SWI-Prolog.  Patch levels are basically minor versions, Minor are major and major is incremented at random long intervals ...   There has been some discussion about this ...

**Comment by mihanus** [comment]
Thanks for your offer. However, in the meantime, I was able to do all fixes my myself so that it now works without the `--traditional` flag. FYI: The most time-consuming issue was the non-atom status of `[]` which resulted in a couple of run-time errors and required some manual data-flow analysis (PAKCS is implemented in Prolog and generates Prolog code...).

**Comment by JanWielemaker** [comment]
Great :+1:  Yes, `[]` can cause some issues.  The analysed porting work also caught a number of bugs though, where `[]` was used as _no value_, _NULL_, _undefined_, ...  but was subsequently interpreted as an ordinary value.   Can you close this?

**Comment by mihanus** [comment]
Ok, I close this issue (although the reported bug still exists, but maybe our conversation helps other people).
