### ISSUE TITLE
slow xref_source/1

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/issues#62]
For some sources, xref_source/1 is extremely slow, or throws "Out of global stack".

The attached slow_xref.pl illustrates this, and shows that time is combinatorial with the qty of inner if-then-elses
[slow_xref.txt](https://github.com/SWI-Prolog/issues/files/1318375/slow_xref.txt)

Hope this helps ;-)

Paul

**Comment by JanWielemaker** [comment]
It was already marked as a bug in the comment (`process_body/3`).  The general problem is probably not solvable, but a much larger class of practical cases can surely become linear.

**Comment by JanWielemaker** [comment]
Pushed swipl-devel@1a41862d46252bd5b42b367131e94e80ab7339b6 that fixes al large class of such issues.  More is possible, notably by checking which variables in a disjunction are used further down the body.

**Comment by JanWielemaker** [comment]
Pushed one more optimization, fixing those cases where variables involved in partial evaluation inside
a disjunction are not shared with the remainder of the body.   You can still construct cases that perform poorly, but the likelihood of hitting them in practice is now pretty low.
