### ISSUE TITLE
Wrong answer to clp(q) integer linear programming goal

### ISSUE THREAD

**Issue by maxicristia** [SWI-Prolog/issues#63]
Hi!

We've found the following error in the clp(q) library.

Version of SWI-Prolog and operating system:

OS: Linux Ubuntu 12.04
SWI-Prolog: Multi-threaded, 32 bits, Version 7.2.3

and

OS: Linux Ubuntu 16.04
SWI-Prolog: 7.6.0

Program that produces the error:

use_module(library(clpq)).
{1 =< Z, Z =< 5, 1 =< X, X =< 5, Z+1 =< X}, bb_inf([Z,X],-Z,Min,_V2).

The answer is:

Min = -3,
_V2 = [3, 5],
{X=<5, _G982=1+Z-X, Z-X=< -1, Z>=1}.

but it should be:

Min = -4,
_V2 = [4, 5],
{X=<5, _G982=1+Z-X, Z-X=< -1, Z>=1}.

According to Frédéric Mesnard this is the answer given by the latest version of Sictus Prolog.

All the best,
  Maxi

**Comment by andreaf96** [comment]
{1 =< Z, Z =< 5, X =< 5, Z+1 =< X, Z >= 4}.
This goal fails with CLP(Q). This error causes entail(Z<4) to be true which discards the value Z = 4.

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/ann-swi-prolog-8-1-22/1867/1
