### ISSUE TITLE
Text in online help contains duplicate chars and graphic characters

### ISSUE THREAD

**Issue by CKalt** [SWI-Prolog/issues#64]
The graphical online help headings include erroneous graphical characters as well as duplicates, making them very hard to read.  All headings seem to be affected.

Screen shot attached.

I'm using Fedora 26 and swipl-7.4.2.  I tried changing the default system font, but was not seeing any improvement.  Any suggestions for a work around would be greatly appreciated.

Thank you
![swiplhelptextbug](https://user-images.githubusercontent.com/3716912/31585739-deac122e-b194-11e7-8dcc-3d03cda1fd13.png)

**Comment by JanWielemaker** [comment]
That is an old bug.  Build a recent version from source or use the website for help.
