### ISSUE TITLE
Inconsistent handling of German umlauts from input 'user'

### ISSUE THREAD

**Issue by wolffw** [SWI-Prolog/issues#65]
```{prolog}
/* Inconsistent handling of German umlauts from input 'user'
 * 
 * test_umlaut.pl (UTF-8)
 * 2017-10-26
 * SWI-Prolog (threaded, 64 bits, version 7.7.1) 
 * running in GNOME-Terminal (bash)
 * on OS: Linux Mint 17.3 Rosa \n \l, kernel 3.16.0-38-generic
 */

:- current_prolog_flag(encoding, utf8).

/*	No problem here ::  */
umlaut(ä).
umlaut(ö).
umlaut(ü).

umlaut_as_atom :-
	findall(X, umlaut(X), Xs),
	format("found:~q~n", [Xs]).

:- umlaut_as_atom.

/*	No problem getting umlauts with
 *  either from keyboard or by copy/paste
 */
get_umlaut :-
	get_single_char(Code),
	put(Code).

/*	But this won't read any umlaut from user
 *  neither from keyboard nor by copy/paste
 */
get_char :-
	get_char(Code),
	format("found:~q~n", [Code]),
	put(Code).

/**/
```

**Comment by JanWielemaker** [comment]
What is your current locale?  `:- current_prolog_flag(encoding, utf8).` should not be needed (and has limited effects as the terminal stream is already initialised).

**Comment by wolffw** [comment]
locale ::


LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

 


 

Gesendet: Freitag, 27. Oktober 2017 um 10:03 Uhr
Von: "Jan Wielemaker" <notifications@github.com>
An: SWI-Prolog/issues <issues@noreply.github.com>
Cc: wolffw <werwolff@web.de>, Author <author@noreply.github.com>
Betreff: Re: [SWI-Prolog/issues] Inconsistent handling of German umlauts from input 'user' (#65)


What is your current locale? :- current_prolog_flag(encoding, utf8). should not be needed (and has limited effects as the terminal stream is already initialised).

**Comment by JanWielemaker** [comment]
Doesn't reproduce:

```
104 ?- get_char(Code).
|: ä

Code = ä.

105 ?- get_single_char(Code).
Code = 228.

106 ?- char_code(C, 228).
C = ä.
```

106 ?- char_code(C, 228).
C = ä.

107 ?- get_umlaut.
ä
true.

108 ?- get_char.
|: ä
found:ä
ä
```

I suspect some inconsistent locale, e.g., core X11 or the terminal emulator not running in UTF-8.

**Comment by wolffw** [comment]
You are right --
there is some intermediate locale-quirk
(bash-script on this terminal works with umlauts,
unfortunately not so swipl)
