### ISSUE TITLE
SWI-Prolog can't delete pack files on Windows

### ISSUE THREAD

**Issue by roschler** [SWI-Prolog/issues#66]
I'm trying to install the PrologMud pack, with SWI-Prolog 7.23 on Windows 8.1:

pack_install(prologmud, [upgrade(true)]).

I have upgrade set to *true* because there appears to be nested dependencies in that pack file that lead to the same dependent packages being installed multiple times.  For example *clause_attvars* is installed multiple times.  Therefore, without the "true" setting the pack installation prints an error and fails as soon as it tries to "blind upgrade" the *clause_attvars* package.

The problem is, the first part of a package upgrade appears to be deleting the existing package files.  When SWI-Prolog tries to do this using *delete_file*, it fails with the following error:

> ERROR: delete_file/1: No permission to delete file `'c:/users/robert/appdata/roaming/swi-prolog/pack/clause_attvars/.git/objects/pack/pack-3236b9d3b310291d5258ad97f51785b6db3dc86e.idx'' (Permission denied)

I tried running SWI-Prolog with administrator permissions and I still get the error.  Is it possible that the error is due to SWI-Prolog using forward slashes instead of backslashes in the path of the file it is trying to delete?  How can I fix this so I can fully install the *prologmud* package?

**Comment by JanWielemaker** [comment]
It certainly has nothing to do with slashes.  SWI-Prolog uses `/` in Prolog, but translates them before accessing the file operations.   There are surely some fixes in more recent versions in the pack system, so I'd first upgrade.   Most likely this won't fix this.  Git objects are read-only.  I don't know how that is reflected in Windows.  Simplest solution is probably to simply delete the pack directory.

Note that recent versions can properly handle multiple paths to the same dependency.

**Comment by roschler** [comment]
Thanks Jan.  I just deleted the pack directory and upgraded to 7.6.1-64-bit.  The pack install worked now.

Do you know when the pengines patch will make it into the next stable release?

**Comment by JanWielemaker** [comment]
?  Pengines seem up-to-date in 7.6.1.

**Comment by roschler** [comment]
Thanks!
