### ISSUE TITLE
sleep/1 can't be aborted under 64 Bit Windows 7

### ISSUE THREAD

**Issue by TheRacoonOfDeath** [SWI-Prolog/issues#7]
Version of SWI-Prolog:
AMD64, Multi-threaded, version 6.6.6

Operating System:
64 Bit Windows 7

How to reproduce the issue:
A full program is not needed, just use a query with sleep
e.g. ?- sleep(10).
While sleep is in action, try to abort (strg c -> a).
The action will not be aborted, but lead to the following message:

```
   Foreign predicate system:sleep/1 did not clear exception: $aborted
```

Especially problematic when working with infinite lists, as testing is only possible if SWI-Prolog is shut down completely after a run, as the program does not terminate and cannot be aborted either.

**Comment by mvolfik** [comment]
Hello, I am not sure if this is the same error (I know very little about prolog below the surface), but I'm getting a similar error when trying to handle Ctrl+C (SIGINT interrupt signal) by throwing an exception:

`a.pl`:

```
main :- on_signal(int, _, throw), sleep(5).
```

```
$ swipl a.pl
?- main.
^C
<keeps sleeping>
<after 5 seconds:>
Thread 1 (main): foreign predicate sleep/1 did not clear exception: 
	error(signal(int,2),context(sleep/1,_7850))
true.

?- 
```

I'm using `SWI-Prolog version 8.4.2 for x86_64-linux`

Should I raise a new issue? Or is this correct behavior? Thanks

**Comment by JanWielemaker** [comment]
This is a bit misleading.    The topic is about Windows.    You claim Linux.   Works fine in 9.x though, at least for me on Fedora.    Please report in a new issue if this is still a problem for you using the 9.x versions.   Include details on the Linux version and how it was build.   E.g., distro package, from source, snap, ....

**Comment by mvolfik** [comment]
I have swipl installed from Mint (-> Ubuntu (or Debian?)) distro package, but just made a build from current master and it works there just fine. Sorry that I didn't check that rightaway
