### ISSUE TITLE
404 on site

### ISSUE THREAD

**Issue by ChipNowacek** [SWI-Prolog/issues#70]
As best I can tell, from here:

[Commercial users](http://www.swi-prolog.org/commercial/index.html)

this link: [Is SWIPL right for me?](http://www.swi-prolog.org/commercial/pldoc/man?section=swiorother)

404s.

**Comment by ChipNowacek** [comment]
Other links on the "USER" menu also load a "Is SWIPL right for me?" link that 404s

**Comment by JanWielemaker** [comment]
Thanks.  Fixed in the source.  Website will be updated on the next release.  Sort term, use the menu from the home page.

**Comment by ChipNowacek** [comment]
Thanks. I'll try to do a PR next time. Not real good at those yet.
