### ISSUE TITLE
dcg_basics:number//1 never terminates when instantiated with a non-number type.

### ISSUE THREAD

**Issue by cowile** [SWI-Prolog/issues#73]
Version: SWI-Prolog version 7.6.0 for x86_64-openbsd6.3
Expected Behavior: immediate failure
Observed Behavior: nontermination
Example Program: swipl -s $PROGRAM
````
:- use_module(library(dcg/basics), [number//1]).
:- dcg_basics:number(nonnumber, _, []).
````

This can be worked around easily by adding a type check before calling number//1, but nontermination is not acceptable behavior for a predicate listed as determinate.

The simple solution is likely a type check inside number//1, but I am a novice and there may be a better way.

**Comment by JanWielemaker** [comment]
You are right.  Fixed with SWI-Prolog/swipl-devel@a4ea2b00b463f296f56f9ab5195d18a25c226f0e (swipl-devel.git).  I'm afraid 7.6 won't be updated.
