### ISSUE TITLE
current_arithmetic_function/1 gives an error if given something not callable, like a number

### ISSUE THREAD

**Issue by ViKomprenas** [SWI-Prolog/issues#74]
```
?- current_arithmetic_function(sin).
false.

?- current_arithmetic_function(sin(A)).
true.

?- current_arithmetic_function(3).
ERROR: Type error: `callable' expected, found `3' (an integer)
ERROR: In:
ERROR:    [8] current_arithmetic_function(3)
ERROR:    [7] <user>
```

(This can be worked around by invoking `callable/1`, naturally.)

**Comment by JanWielemaker** [comment]
I don't see a very good argument to remove this type checking.   Yes, you can go through an arithmetic expression without stumbling on the numbers (you'd get __false__ though), but you still need to handle the variables special (depending on whether the expression is already fully instantiated or not).   So, I do not think it helps much in the tasks you'd use this predicate for while raising errors in general does simplify debugging.

**Comment by ViKomprenas** [comment]
I'm expecting/suggesting that it fail, which I think mitigates your concern. I'm not exactly experienced in Prolog, though.

**Comment by JanWielemaker** [comment]
Give me the use case where this would significantly simplify the code.

**Comment by ViKomprenas** [comment]
There isn't one, really; I just thought it odd that a predicate specifically designed to work with math throws an error for numbers.
