### ISSUE TITLE
clauses of dynamic pred mangled after reconsult

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/issues#77]
Hi Jan
I use the `foobar(_) :- fail.` clause below to force PDT to show foobar/1 in the Eclipse Outline, at least until someone fixes PDT :-/
But this workaround seems to show up a bug in 64-bit 7.6.4 (both Windows and Linux) whereby consult/1 loses my asserted facts, and misreports the qty of rules :-/

foobar.pl has
```
:- dynamic foobar/1.
foobar(_) :- fail.
```
run.pl retracts all clauses, then asserts ten facts.
predicate_property reports
```
number_of_clauses(10)
number_of_rules(1)
```
where the 1 should be a 0.
After `consult(foobar)` predicate_property reports
```
number_of_clauses(1)
number_of_rules(2)
```
where the 1 should still be ten, and the 2 should be a 1.
[foobar.zip](https://github.com/SWI-Prolog/issues/files/2380715/foobar.zip)

**Comment by anionic** [comment]
Misbehaviour is triggered by retracting `foobar() :- fail.`
If I instead remove only facts
```
forall(
  clause(foobar(_), true, Ref),
  erase(Ref)
),
```
and leave my invisible rule, all is OK, i.e. I have a workaround.

**Comment by JanWielemaker** [comment]
Indeed looks like a bug.  I'll have a look, probably tomorrow.  Would be nice if this hacking wasn't required in the first place though ...

**Comment by JanWielemaker** [comment]
Pushed two fixes.  One for the incorrectly removed dynamic clauses and one for the wrong `number_of_rules` count.  Thanks.
