### ISSUE TITLE
handling multiple session cookies in HTTP request

### ISSUE THREAD

**Issue by anionic** [SWI-Prolog/issues#8]
summary: s/memberchk/member/ in library(http/http_session) line 288 (6.6.6 or 7.1.26)
Empirically, and as reported variously in web forums, modern browsers may send a request with two or more cookies with the same name, including both defunct & valid sessionid cookies - dunno why but it happens.
http_session/3 commits to the first cookie with the expected name, and logged-in users may get "you are not logged in".
The fix above will commit to the first *valid* sessionid if any, and the user will see the expected behaviour.

**Comment by JanWielemaker** [comment]
Thanks.  Applied in SWI-Prolog/packages-http@f06f35ced9331d7660a2948aa37d704050fc59fd
