### ISSUE TITLE
(dynamic)/1 bug in assert/1

### ISSUE THREAD

**Issue by Shyam-Has-Your-Anomaly-Mitigated** [SWI-Prolog/issues#81]
I am following the [official steps](http://www.swi-prolog.org/bug.html).

### Step 01.
```
linux$ swipl -v
SWI-Prolog version 7.6.4 for i386
```
### Step 10.
This is a knowledge base.
```
#!/usr/bin/env swipl
a(1).
```
This is the interactor.
```
?- a(X).
X = 1.

?- retract(a(1)).
ERROR: No permission to modify static procedure `a/1'
ERROR: Defined at /home/edu/Downloads/Prolog/experiments/meta.pl:2
ERROR: In:
ERROR:    [8] retract(a(1))
ERROR:    [7] <user>
?- assert(a(2)).
true.

?- retract(a(1)).
true.

?- a(X).
X = 2.
```
The query `assert(a(1)).` performs the same as `assert(a(2)).`; I just think `assert(a(2)).` demonstrates the propagation of the bug.
This seems to only happen when you assert functors of the same arity in the knowledge base.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed with 5deb1b053f9c6e25c469783fd79858ee783b5c15, which should appear in
8.0.1 and and 8.1.1.
