### ISSUE TITLE
swipl 8.0.1 / PL_thread_attach_engine(attr) crashes if attr == NULL

### ISSUE THREAD

**Issue by clausengel** [SWI-Prolog/issues#86]
A call of "PL_thread_attach_engine" with attributes==NULL crashes on line 5337 in file "pl-thread.c" (calling "copy_local_data").

**Comment by JanWielemaker** [comment]
Yes.  A fix is already in the stable git (d5842f4a0e714b26f48fd9d8369178068edc4f63).  Will be ok in 8.0.2, probably to be released early March.
