### ISSUE TITLE
Satisfiable goal fails in CLP(Q)

### ISSUE THREAD

**Issue by andreaf96** [SWI-Prolog/issues#93]
Hi, I've found an issue with clpq.
The bug I am reporting is the direct cause of the bug reported here: https://github.com/SWI-Prolog/issues/issues/63

The following goal returns false even though it should have a solution.

{Z>=0, Z =< 2, X =< 1,X>=Z , Z >= 1}.

The only actual solution should be X=Z=1.
Please note that the bug occurs even if we swap X>=Z with X=Z.

{Z>=0, Z =< 2, X =< 1,X=Z , Z >= 1}.

**Comment by andreaf96** [comment]
I think I've solved it here https://github.com/andreaf96/packages-clpqr/commit/157cf2f980db204cccb3a2aece3e0553ff3b71c9 @JanWielemaker

**Comment by JanWielemaker** [comment]
This issue has been mentioned on **SWI-Prolog**. There might be relevant details there:

https://swi-prolog.discourse.group/t/ann-swi-prolog-8-1-22/1867/1
